apiVersion: v1
kind: BuildConfig
metadata:
  name: ruby-mysql-app-pipeline
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/johnfosborneiii/ruby-mysql-app 
      ref: ocp33-pipeline 
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  output:
    to:
      kind: ImageStreamTag
      name: 'ruby-mysql-app:latest'
status:
